"""Regression tests for TIDAS export schema cleanup (Phase 1 structure fixes)."""
from __future__ import annotations

from app.tidas_export import (
    ExportReport,
    _build_flow_data,
    _build_tidas_exchange,
    _classification_information,
    _common_admin_information,
    _process_modelling_and_validation,
    _localized_items,
)
from app.models import FlowRecord


# ── _localized_items ──────────────────────────────────────────────────────


def test_localized_items_english_only():
    """Pure English text must produce 'en', not 'zh'."""
    items = _localized_items("Generated by Nebula LCA")
    assert len(items) == 1
    assert items[0]["@xml:lang"] == "en"
    assert items[0]["#text"] == "Generated by Nebula LCA"


def test_localized_items_chinese():
    """Chinese text must produce 'zh'."""
    items = _localized_items("未指定")
    assert len(items) == 1
    assert items[0]["@xml:lang"] == "zh"
    assert items[0]["#text"] == "未指定"


def test_localized_items_bilingual():
    """Chinese + English must produce two items with correct lang tags."""
    items = _localized_items("未指定", "Unspecified")
    assert len(items) == 2
    assert items[0]["@xml:lang"] == "zh"
    assert items[0]["#text"] == "未指定"
    assert items[1]["@xml:lang"] == "en"
    assert items[1]["#text"] == "Unspecified"


def test_localized_items_no_duplicate():
    """When zh and en are identical, only one item is emitted."""
    items = _localized_items("TEST", "TEST")
    assert len(items) == 1
    assert items[0]["@xml:lang"] == "en"


def test_localized_items_no_english_with_zh_lang():
    """English text must never get @xml:lang='zh'."""
    items = _localized_items("Generated by Nebula LCA", "Generated by Nebula LCA")
    for item in items:
        assert item["@xml:lang"] != "zh" or not isinstance(item["#text"], str) or any(
            '\u4e00' <= ch <= '\u9fff' for ch in item["#text"]
        )


# ── _build_tidas_exchange ────────────────────────────────────────────────


def test_exchange_numeric_dataSetInternalID():
    """Exchange dataSetInternalID must be a numeric string."""
    exchange = _build_tidas_exchange(
        {"@dataSetInternalID": "5", "flow_uuid": "f1", "direction": "Output", "amount": 10}
    )
    assert exchange["@dataSetInternalID"] == "5"


def test_exchange_amounts_are_strings():
    """meanAmount and resultingAmount must be string values."""
    exchange = _build_tidas_exchange(
        {"@dataSetInternalID": "0", "flow_uuid": "f1", "direction": "Output", "amount": 42}
    )
    assert isinstance(exchange["meanAmount"], str)
    assert exchange["meanAmount"] == "42"
    assert isinstance(exchange["resultingAmount"], str)
    assert exchange["resultingAmount"] == "42"


def test_exchange_allocation_fraction_no_percent():
    """Allocation fraction must be a number string without '%' sign."""
    report = ExportReport()
    factors = {"0": 0.38, "1": 0.62}
    exchange = _build_tidas_exchange(
        {"@dataSetInternalID": "0", "flow_uuid": "f1", "direction": "Output", "amount": 1},
        allocation_factors=factors,
        ref_internal_id="0",
    )
    fraction = exchange["allocations"]["allocation"]["@allocatedFraction"]
    assert "%" not in fraction
    assert fraction == "38"


def test_exchange_preserves_original_port_id():
    """json_tg.originalInternalId must carry the raw port id."""
    exchange = _build_tidas_exchange(
        {
            "@dataSetInternalID": "3",
            "internal_id": "port-abc-123",
            "flow_uuid": "f1",
            "direction": "Input",
            "amount": 5,
        }
    )
    assert "json_tg" in exchange
    assert exchange["json_tg"]["originalInternalId"] == "port-abc-123"


def test_exchange_no_empty_referencesToDataSource_or_allocations():
    """Exchanges must not contain referencesToDataSource or empty allocations."""
    exchange = _build_tidas_exchange(
        {"@dataSetInternalID": "0", "flow_uuid": "f1", "direction": "Input", "amount": 1}
    )
    assert "referencesToDataSource" not in exchange
    if "allocations" in exchange:
        # allocations only present for Outputs with factors
        assert exchange["allocations"] != {"allocation": {}}


# ── _common_admin_information ────────────────────────────────────────────


def test_admin_info_no_empty_reference():
    """referenceToPersonOrEntityEnteringTheData must not be empty dict."""
    admin = _common_admin_information()
    ref = admin["dataEntryBy"]["common:referenceToPersonOrEntityEnteringTheData"]
    assert ref != {}
    assert "@refObjectId" in ref


def test_admin_info_has_permanentDataSetURI():
    """permanentDataSetURI must be present when provided."""
    admin = _common_admin_information(permanent_uri="urn:nebula-lca:tidas:abc-123")
    assert admin["publicationAndOwnership"]["common:permanentDataSetURI"] == "urn:nebula-lca:tidas:abc-123"


def test_admin_info_no_preceding_version():
    """referenceToPrecedingDataSetVersion must not appear."""
    admin = _common_admin_information()
    assert "referenceToPrecedingDataSetVersion" not in admin["publicationAndOwnership"]


def test_flow_dataset_omits_empty_optional_text_fields():
    class _FakeDb:
        def get(self, model, key):
            assert model is FlowRecord
            assert key == "flow-1"
            return FlowRecord(
                flow_uuid="flow-1",
                flow_name="test flow",
                flow_type="Product flow",
                default_unit="kg",
                unit_group="Units of mass",
                source="test",
            )

    flow_data = _build_flow_data(_FakeDb(), "flow-1", ExportReport())
    dsi = flow_data["flowDataSet"]["flowInformation"]["dataSetInformation"]

    assert "common:other" not in dsi
    assert "common:synonyms" not in dsi


def test_process_validation_uses_catalog_skeleton():
    mv = _process_modelling_and_validation()
    validation = mv["validation"]

    assert "review" in validation
    assert "complianceDeclarations" in mv


# ── _classification_information ──────────────────────────────────────────


def test_classification_uses_catalog_when_dataset_type_provided():
    """When dataset_type matches a catalog entry, catalog is used instead of legacy split."""
    ci = _classification_information("air", dataset_type="flow")
    classes = ci["common:classification"]["common:class"]
    # Catalog fallback has entries for "flow" type (Emissions, etc.)
    assert len(classes) >= 1
    assert all("@classId" in c and "@level" in c for c in classes)


def test_classification_legacy_fallback_when_type_unknown():
    """When dataset_type doesn't match catalog, legacy ; split is used as fallback."""
    ci = _classification_information("ef_tiangong;air", dataset_type="unknown_type_xyz")
    classes = ci["common:classification"]["common:class"]
    assert len(classes) == 2
    assert classes[0]["#text"] == "ef_tiangong"
    assert classes[0]["@level"] == "0"
    assert classes[1]["#text"] == "air"
    assert classes[1]["@level"] == "1"


def test_classification_empty_fallback_to_legacy():
    """Empty label with no catalog match falls back to 'Unclassified' via legacy path."""
    ci = _classification_information(None, dataset_type="unknown_type_xyz")
    assert ci["common:classification"]["common:class"][0]["#text"] == "Unclassified"

    ci2 = _classification_information("", dataset_type="unknown_type_xyz")
    assert ci2["common:classification"]["common:class"][0]["#text"] == "Unclassified"
