"""Regression tests for EF3.1 runtime artifact manifest and integrity.

Covers:
1. generate_ef31_runtime_csvs() produces manifest.json with all required fields.
2. active_manifest.json points to the runtime generated by the correct import job.
3. The manifest preserves cf_matched / cf_unmatched / cf_ambiguous counts.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest


class TestRuntimeManifestFields:
    """Verify manifest.json structure from generate_ef31_runtime_csvs."""

    def _write_job_artifacts(self, tmp_path: Path, job_dir: Path) -> None:
        """Write minimal JSON artifacts for a fake EF3.1 import job."""
        # elementary_flows.json
        (job_dir / "elementary_flows.json").write_text(json.dumps([
            {
                "flow_uuid": "08a91e70-3ddc-11dd-923d-0050c2490048",
                "flow_name": "carbon dioxide (fossil)",
                "flow_type": "Elementary flow",
                "default_unit": "kg",
                "unit_group": "Units of mass",
                "compartment": "air",
            },
            {
                "flow_uuid": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                "flow_name": "methane",
                "flow_type": "Elementary flow",
                "default_unit": "kg",
                "unit_group": "Units of mass",
                "compartment": "air",
            },
        ]))

        # all_cfs.json — two CFs: one matched, one unmatched
        (job_dir / "all_cfs.json").write_text(json.dumps([
            {
                "ecspold_index": 0,
                "source_flow_id": "08a91e70-3ddc-11dd-923d-0050c2490048",
                "source_indicator_id": "climate_change",
                "value": 0.44,
                "unit": "kg CO2-eq / kg",
            },
            {
                "ecspold_index": 1,
                "source_flow_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                "source_indicator_id": "climate_change",
                "value": 25.0,
                "unit": "kg CO2-eq / kg",
            },
        ]))

        # cf_matches_all.json — first CF matched, second CF not matched
        (job_dir / "cf_matches_all.json").write_text(json.dumps({
            "matched": [
                {
                    "ecspold_index": 0,
                    "matched_flow_uuid": "08a91e70-3ddc-11dd-923d-0050c2490048",
                    "matched_flow_name": "carbon dioxide, fossil",
                    "match_type": "exact",
                    "cf_method": "EF v3.1",
                    "cf_indicator": "Climate change",
                    "cf_value": 0.44,
                },
            ],
            "unmatched": [
                {
                    "ecspold_index": 1,
                },
            ],
            "ambiguous": [],
        }))

        # indicators.json
        (job_dir / "indicators.json").write_text(json.dumps([
            {
                "indicator_id": "climate_change",
                "indicator_name": "Climate change",
                "method": "EF v3.1",
                "category": "Climate change",
                "indicator": "Climate change",
                "indicator_unit": "kg CO2-eq",
            },
        ]))

    def test_manifest_contains_required_fields(self, tmp_path: Path) -> None:
        """generate_ef31_runtime_csvs produces manifest.json with all required keys."""
        from app.services.ef31_runtime_csv import generate_ef31_runtime_csvs

        job_dir = tmp_path / "job_001"
        job_dir.mkdir()
        self._write_job_artifacts(tmp_path, job_dir)
        output_root = tmp_path / "runtime"
        output_root.mkdir()

        result = generate_ef31_runtime_csvs(
            job_id="job_001",
            output_root=output_root,
            _job_dir_override=job_dir,
        )

        # Verify return dict has expected keys
        assert "flows_count" in result
        assert "indicators_count" in result
        assert "factors_count" in result
        assert "cf_matched" in result
        assert "cf_unmatched" in result
        assert "cf_ambiguous" in result

        # Verify manifest.json on disk (written to output_root/{job_id}/)
        manifest_path = output_root / "job_001" / "manifest.json"
        assert manifest_path.exists()
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        assert manifest["job_id"] == "job_001"
        assert "flows_count" in manifest
        assert "indicators_count" in manifest
        assert "factors_count" in manifest
        assert "cf_matched" in manifest
        assert "cf_unmatched" in manifest
        assert "cf_ambiguous" in manifest

    def test_manifest_preserves_cf_counts(self, tmp_path: Path) -> None:
        """CF matched/unmatched counts should be preserved in manifest."""
        from app.services.ef31_runtime_csv import generate_ef31_runtime_csvs

        job_dir = tmp_path / "job_002"
        job_dir.mkdir()
        self._write_job_artifacts(tmp_path, job_dir)
        output_root = tmp_path / "runtime_002"
        output_root.mkdir()

        generate_ef31_runtime_csvs(
            job_id="job_002",
            output_root=output_root,
            _job_dir_override=job_dir,
        )

        manifest = json.loads((output_root / "job_002" / "manifest.json").read_text(encoding="utf-8"))

        # We wrote 2 CFs, 1 matched, 1 unmatched, 0 ambiguous
        assert manifest["cf_matched"] == 1
        assert manifest["cf_unmatched"] == 1
        assert manifest["cf_ambiguous"] == 0

    def test_active_manifest_points_to_correct_runtime(self, tmp_path: Path) -> None:
        """active_manifest.json should point to the runtime generated by the import job."""
        from app.services.ef31_runtime_csv import generate_ef31_runtime_csvs

        job_dir = tmp_path / "job_003"
        job_dir.mkdir()
        self._write_job_artifacts(tmp_path, job_dir)
        output_root = tmp_path / "runtime_003"
        output_root.mkdir()

        generate_ef31_runtime_csvs(
            job_id="job_003",
            output_root=output_root,
            _job_dir_override=job_dir,
        )

        active_manifest_path = output_root / "active_manifest.json"
        assert active_manifest_path.exists()
        active = json.loads(active_manifest_path.read_text(encoding="utf-8"))
        # active_manifest.json should reference the artifact dir within the job
        assert active.get("active") is True
        assert active.get("job_id") == "job_003"
        # artifact_dir should contain the job_id
        assert "job_003" in str(active.get("artifact_dir", ""))

    def test_tiny_runtime_does_not_replace_broad_default_active_manifest(self, tmp_path: Path, monkeypatch) -> None:
        """Small preview runtimes should not downgrade the default ecoinvent runtime."""
        import app.services.ef31_runtime_csv as runtime_csv

        output_root = tmp_path / "runtime_default"
        output_root.mkdir()
        broad_active = {
            "job_id": "lcia-official-3.11",
            "artifact_dir": str(output_root / "lcia-official-3.11"),
            "flows_count": 9795,
            "indicators_count": 50,
            "factors_count": 54215,
            "active": True,
        }
        (output_root / "active_manifest.json").write_text(
            json.dumps(broad_active),
            encoding="utf-8",
        )
        monkeypatch.setattr(runtime_csv, "DEFAULT_EF31_RUNTIME_ROOT", output_root)

        job_dir = tmp_path / "tiny_job"
        job_dir.mkdir()
        self._write_job_artifacts(tmp_path, job_dir)

        result = runtime_csv.generate_ef31_runtime_csvs(
            job_id="tiny_job",
            output_root=output_root,
            _job_dir_override=job_dir,
        )

        active = json.loads((output_root / "active_manifest.json").read_text(encoding="utf-8"))
        manifest = json.loads((output_root / "tiny_job" / "manifest.json").read_text(encoding="utf-8"))
        assert result["active"] is False
        assert manifest["active"] is False
        assert active["job_id"] == "lcia-official-3.11"

    def test_runtime_csv_content(self, tmp_path: Path) -> None:
        """Verify the generated CSVs have correct content."""
        import csv

        from app.services.ef31_runtime_csv import generate_ef31_runtime_csvs

        job_dir = tmp_path / "job_004"
        job_dir.mkdir()
        self._write_job_artifacts(tmp_path, job_dir)
        output_root = tmp_path / "runtime_004"
        output_root.mkdir()

        result = generate_ef31_runtime_csvs(
            job_id="job_004",
            output_root=output_root,
            _job_dir_override=job_dir,
        )

        # lcia_factors.csv should only contain matched CFs (1 row for matched CO2)
        factors_path = output_root / "job_004" / "lcia_factors.csv"
        assert factors_path.exists()
        with open(factors_path, encoding="utf-8", newline="") as f:
            reader = csv.DictReader(f, delimiter=";")
            rows = list(reader)
        # Only matched CFs are written to factors
        assert len(rows) == 1
        assert float(rows[0]["coefficient"]) == 0.44

        # flow_index.csv should contain all elementary flows
        flow_index_path = output_root / "job_004" / "flow_index.csv"
        with open(flow_index_path, encoding="utf-8", newline="") as f:
            reader = csv.DictReader(f, delimiter=";")
            flow_rows = list(reader)
        assert len(flow_rows) == 2

        # indicator_index.csv should have at least 1 indicator
        indicator_index_path = output_root / "job_004" / "indicator_index.csv"
        with open(indicator_index_path, encoding="utf-8-sig", newline="") as f:
            reader = csv.DictReader(f, delimiter=";")
            ind_rows = list(reader)
        assert len(ind_rows) >= 1
