"""TIDAS Bundle Export Module.

Exports project models to TIDAS bundle ZIP format compatible with existing importers.
"""

import io
import json
import zipfile
import uuid
from datetime import datetime
from typing import Any

from sqlalchemy.orm import Session

from .allocation import calculate_product_allocation, collect_multi_product_unit_group_violations
from .flow_unit_semantics import (
    build_unit_reference_maps,
    collect_flow_default_unit_conversion_violations,
    resolve_flow_port_unit_semantics,
)
from .models import Model, ModelVersion, FlowRecord, ReferenceProcess, UnitDefinition
from .schemas import HybridGraph
from .tidas_reference import get_tidas_flow_property_reference, load_tidas_reference_seed
from .source_policy import (
    classify_flow_source,
    _collect_biosphere_flow_uuids,
    _batch_lookup_flow_sources,
)

TIDAS_DEFAULT_DATASET_VERSION = "01.01.000"
TIDAS_ILCD_SCHEMA_VERSION = "1.1"
TIDAS_PLACEHOLDER_ZH = "未指定"
TIDAS_PLACEHOLDER_EN = "Unspecified"
TIDAS_ROUTE_PLACEHOLDER_ZH = "未指定工艺路线"
TIDAS_ROUTE_PLACEHOLDER_EN = "Unspecified route"
TIDAS_GENERATED_COMMENT = "Generated by Nebula LCA"
TIDAS_DEFAULT_YEAR = 2026

TIDAS_DATASET_FORMAT_REF = {
    "@refObjectId": "a97a0155-0234-4b87-b4ce-a45da52f2a40",
    "@type": "source data set",
    "@uri": "../sources/a97a0155-0234-4b87-b4ce-a45da52f2a40.xml",
    "@version": "03.00.003",
    "common:shortDescription": [
        {"#text": "ILCD format", "@xml:lang": "en"},
        {"#text": "ILCD 数据格式", "@xml:lang": "zh"},
    ],
}

TIDAS_OWNERSHIP_REF = {
    "@refObjectId": "f4b4c314-8c4c-4c83-968f-5b3c7724f6a8",
    "@type": "contact data set",
    "@uri": "../contacts/f4b4c314-8c4c-4c83-968f-5b3c7724f6a8.xml",
    "@version": "01.00.000",
    "common:shortDescription": [
        {"#text": "Tiangong LCA Data Working Group", "@xml:lang": "en"},
        {"#text": "天工LCA数据团队", "@xml:lang": "zh"},
    ],
}

TIDAS_COMPLIANCE_REF = {
    "@refObjectId": "d92a1a12-2545-49e2-a585-55c259997756",
    "@type": "source data set",
    "@uri": "../sources/d92a1a12-2545-49e2-a585-55c259997756.xml",
    "common:shortDescription": {"#text": "ILCD Data Network - Entry-level", "@xml:lang": "en"},
}


class ExportError(Exception):
    """Raised when export validation fails."""

    pass


class ExportWarning:
    """Represents a non-blocking warning during export."""

    def __init__(self, category: str, message: str, context: dict | None = None):
        self.category = category
        self.message = message
        self.context = context or {}

    def to_dict(self) -> dict:
        return {
            "category": self.category,
            "message": self.message,
            "context": self.context,
        }


class ExportReport:
    """Collects export diagnostics."""

    def __init__(self):
        self.warnings: list[ExportWarning] = []
        self.errors: list[str] = []
        self.flow_count = 0
        self.process_count = 0
        self.exported_model_count = 0
        # Allocation tracking for multi-product processes
        self.multi_product_process_count = 0
        self.allocation_warnings: list[ExportWarning] = []
        self.manual_allocation_required_processes: list[str] = []
        self.reference_flow_by_process: dict[str, str] = {}

    def add_warning(self, category: str, message: str, context: dict | None = None):
        self.warnings.append(ExportWarning(category, message, context))
        if category == "allocation":
            self.allocation_warnings.append(ExportWarning(category, message, context))

    def add_error(self, message: str):
        self.errors.append(message)

    def has_errors(self) -> bool:
        return len(self.errors) > 0

    def to_dict(self) -> dict:
        return {
            "exported_at": datetime.utcnow().isoformat(),
            "flow_count": self.flow_count,
            "process_count": self.process_count,
            "exported_model_count": self.exported_model_count,
            "multi_product_process_count": self.multi_product_process_count,
            "allocation_warnings": [w.to_dict() for w in self.allocation_warnings],
            "manual_allocation_required_processes": self.manual_allocation_required_processes,
            "reference_flow_by_process": self.reference_flow_by_process,
            "warnings": [w.to_dict() for w in self.warnings],
            "errors": self.errors,
        }


PTS_TIDAS_EXPORT_ERROR_CODE = "PTS_MODULE_NOT_SUPPORTED_FOR_TIDAS_EXPORT"
PTS_TIDAS_EXPORT_MESSAGE = (
    "Current TIDAS export does not support PTS modules. "
    "Please unpack PTS in the modeling canvas before exporting unit process, market process, or LCI data."
)


SOURCE_SPACE_TIDAS_BLOCKED_CODE = "TIANGONG_TIDAS_BLOCKED_BY_SOURCE_SPACE"
SOURCE_SPACE_TIDAS_BLOCKED_MESSAGE = (
    "开源版不支持 EF / ecoinvent 基本流的自动转换。模型中包含 ecoinvent 或其他非 EF/Tiangong 来源的基本流，不能导出天工 TIDAS。"
)

# Source-space classification constants
SOURCE_SPACE_EF_TIANGONG = "ef_tiangong"
SOURCE_SPACE_ECOSPREAD = "ecoinvent"  # legacy naming preserved
SOURCE_SPACE_UNKNOWN = "unknown"

# Tokens that explicitly indicate EF / TianGong source space.
# These are checked as whole-word matches against the lower-cased source string
# to avoid false positives like "reference" → "ef".
EF_TIANGONG_TOKENS = ("tiangong", "ef3.1", "ef31", "official")
# EF is matched as a stand-alone token, not as a substring:
#   "ef"        → match
#   "reference" → no match (no "ef" token boundary)
#   "ef3.1"     → also matched above, but "ef" won't catch it anyway
EF_TOKEN = "ef"


def _classify_source_space(source: str | None) -> str:
    """Classify a flow's source space from its FlowRecord.source field.

    Returns one of:
        SOURCE_SPACE_EF_TIANGONG  – matches EF / TianGong tokens (case-insensitive)
        SOURCE_SPACE_ECOSPREAD    – contains "ecoinvent"
        SOURCE_SPACE_UNKNOWN      – empty / unclassifiable

    Token matching rules (avoid "reference"/"undefined" false positives):
        - Multi-char tokens (tiangong, ef3.1, ef31, official): word-boundary match
          using split() + set containment.
        - "ef" (stand-alone only): split() + set containment.
          "reference" → "reference" in split set → no "ef" token found.
          "ef3.1.104" → tokens: ["ef3.1.104"] → matches "ef3.1" as sub-token.
    """
    if not source:
        return SOURCE_SPACE_UNKNOWN

    src_lower = source.lower()
    src_tokens = set(src_lower.split())

    # ecoinvent check (no false-positive risk since EF/TG tokens don't contain it)
    if "ecoinvent" in src_lower:
        return SOURCE_SPACE_ECOSPREAD

    # Check each token for EF/TianGong prefixes.
    # "ef3.1.104".split() → {"ef3.1.104"} → startswith("ef3.1") → match
    # "reference".split() → {"reference"} → no match (safe)
    # "undefined".split() → {"undefined"} → no match (safe)
    for token in src_tokens:
        for match_token in EF_TIANGONG_TOKENS:
            if token == match_token or token.startswith(match_token + ".") or token.startswith(match_token + "-"):
                return SOURCE_SPACE_EF_TIANGONG
        # Stand-alone "ef" check: exact match only (already excluded by ef3.1/ef31 above)
        if token == EF_TOKEN:
            return SOURCE_SPACE_EF_TIANGONG

    return SOURCE_SPACE_UNKNOWN


def _scan_source_space(
    db: Session, flow_uuids: set[str], report: ExportReport
) -> bool:
    """Scan elementary flows in the graph for unsupported source spaces.

    Logic:
    - Only elementary flows are subject to source-space blocking.
    - Product / waste flows are allowed regardless of source.
    - If ANY elementary flow has source space != ef_tiangong, block export.

    Returns:
        True if source-space check passed (no blocking issues).
        False if blocking issues were found (errors/warnings already added to report).
    """
    # Collect elementary flows grouped by source space
    blocked_by_space: dict[str, list[str]] = {}  # space -> [flow_uuids]

    for flow_uuid in flow_uuids:
        flow_record = db.get(FlowRecord, flow_uuid)
        if flow_record is None:
            continue  # already reported as missing

        # Only elementary flows are subject to source-space check.
        # Normalize common DB variations: "Elementary flow", "elementary_flow",
        # "Elementary_flow", "elementary flow", etc.
        ft = (flow_record.flow_type or "").replace("_", " ").strip().lower()
        if ft != "elementary flow":
            continue

        source = str(flow_record.source or "").strip()
        space = _classify_source_space(source)

        if space == SOURCE_SPACE_EF_TIANGONG:
            # Allowed – no action needed
            continue

        blocked_by_space.setdefault(space, []).append(flow_uuid)

    # If no blocked elementary flows, everything is fine
    if not blocked_by_space:
        return True

    # Report blocking errors per source space
    all_blocked_uuids: list[str] = []
    for space, uuids in blocked_by_space.items():
        all_blocked_uuids.extend(uuids)
        count = len(uuids)
        preview_uuids = uuids[:10]  # first 10 for the warning context

        if space == SOURCE_SPACE_UNKNOWN:
            detail = f"basic flow source unknown: {', '.join(preview_uuids)}"
            if count > 10:
                detail = f"{detail}, ..."
            msg = f"{SOURCE_SPACE_TIDAS_BLOCKED_MESSAGE} (source-space unknown, {count} flow(s))"
        elif space == SOURCE_SPACE_ECOSPREAD:
            detail = f"ecoinvent basic flows: {', '.join(preview_uuids)}"
            if count > 10:
                detail = f"{detail}, ..."
            msg = f"{SOURCE_SPACE_TIDAS_BLOCKED_MESSAGE} (ecoinvent basic flows, {count} flow(s))"
        else:
            detail = f"unsupported source '{space}': {', '.join(preview_uuids)}"
            if count > 10:
                detail = f"{detail}, ..."
            msg = f"{SOURCE_SPACE_TIDAS_BLOCKED_MESSAGE} (unsupported source '{space}', {count} flow(s))"

        error_code = f"{SOURCE_SPACE_TIDAS_BLOCKED_CODE}: {space}"
        report.add_error(f"{error_code}: {msg}")
        report.add_warning(
            "unsupported_source_space",
            msg,
            {
                "source_space": space,
                "blocked_count": count,
                "flow_uuids": preview_uuids,
            },
        )

    return False


def _get_model_version(db: Session, project_id: str, version: int | None = None) -> ModelVersion | None:
    """Fetch model version by project_id and optional version number.

    If version is None, fetches the latest version.
    """
    query = db.query(ModelVersion).filter(ModelVersion.model_id == project_id)

    if version is not None:
        return query.filter(ModelVersion.version == version).first()

    # Latest version
    latest = query.order_by(ModelVersion.version.desc()).first()
    return latest


def _find_pts_nodes(graph_json: dict) -> list[dict]:
    """Return PTS nodes from a graph JSON payload."""
    pts_nodes: list[dict] = []
    for node in graph_json.get("nodes", []):
        if isinstance(node, dict) and str(node.get("node_kind") or "").strip() == "pts_module":
            pts_nodes.append(node)
    return pts_nodes


def _add_pts_export_blocker(report: ExportReport, pts_nodes: list[dict]) -> None:
    """Record a blocking export error for graphs that still contain PTS modules."""
    pts_refs = [
        str(node.get("process_uuid") or node.get("pts_uuid") or node.get("id") or "").strip()
        for node in pts_nodes
    ]
    pts_refs = [ref for ref in pts_refs if ref]
    detail = PTS_TIDAS_EXPORT_MESSAGE
    if pts_refs:
        detail = f"{detail} PTS nodes: {', '.join(pts_refs[:5])}"
        if len(pts_refs) > 5:
            detail = f"{detail}, ..."
    report.add_error(f"{PTS_TIDAS_EXPORT_ERROR_CODE}: {detail}")
    report.add_warning(
        "unsupported_pts_export",
        PTS_TIDAS_EXPORT_MESSAGE,
        {"pts_nodes": pts_refs},
    )


def _build_flow_type_map(db: Session, flow_uuids: set[str]) -> dict[str, str]:
    """Build a map of flow_uuid -> flow_type for quick lookup.

    Args:
        db: Database session
        flow_uuids: Set of flow UUIDs to look up

    Returns:
        Dict mapping flow_uuid to flow_type
    """
    flow_type_map = {}
    for flow_uuid in flow_uuids:
        flow_record = db.get(FlowRecord, flow_uuid)
        if flow_record:
            flow_type_map[flow_uuid] = flow_record.flow_type
    return flow_type_map


def _extract_graph_data(graph_json: dict) -> tuple[set[str], set[str]]:
    """Extract unique flow_uuids and process_uuids from graph.

    Returns:
        Tuple of (flow_uuids, process_uuids)
    """
    flow_uuids: set[str] = set()
    process_uuids: set[str] = set()

    nodes = graph_json.get("nodes", [])
    for node in nodes:
        if not isinstance(node, dict):
            continue

        # Use process_uuid from node, fallback to id only if process_uuid missing
        process_uuid = node.get("process_uuid") or node.get("id")
        if process_uuid:
            process_uuids.add(str(process_uuid))

        # Collect flow UUIDs from ports
        for bucket in ("inputs", "outputs"):
            ports = node.get(bucket, [])
            for port in ports:
                if not isinstance(port, dict):
                    continue
                flow_uuid = port.get("flowUuid")
                if flow_uuid:
                    flow_uuids.add(str(flow_uuid))

    # Also check exchanges if present
    exchanges = graph_json.get("exchanges", [])
    for exchange in exchanges:
        if not isinstance(exchange, dict):
            continue
        flow_uuid = exchange.get("flowUuid")
        if flow_uuid:
            flow_uuids.add(str(flow_uuid))

    return flow_uuids, process_uuids


def _repair_target_for_unit_group(graph_json: dict, unit_group: str) -> dict:
    target = {"unit_group": unit_group, "repair_target": "unit_group"}
    needle = str(unit_group or "").strip().lower()
    for node in graph_json.get("nodes", []) or []:
        if not isinstance(node, dict):
            continue
        for port in (node.get("inputs") or []) + (node.get("outputs") or []):
            current = str(port.get("unitGroup") or port.get("unit_group") or "").strip().lower()
            if current == needle:
                target.update({
                    "node_id": node.get("id"),
                    "process_uuid": node.get("process_uuid"),
                    "port_id": port.get("id"),
                    "flow_uuid": port.get("flowUuid") or port.get("flow_uuid"),
                })
                return target
    return target


def _repair_target_for_flow_uuid(graph_json: dict, flow_uuid: str) -> dict:
    target = {"flow_uuid": flow_uuid, "repair_target": "flow"}
    needle = str(flow_uuid or "").strip().lower()
    for node in graph_json.get("nodes", []) or []:
        if not isinstance(node, dict):
            continue
        for port in (node.get("inputs") or []) + (node.get("outputs") or []):
            current = str(port.get("flowUuid") or port.get("flow_uuid") or "").strip().lower()
            if current == needle:
                target.update({
                    "node_id": node.get("id"),
                    "process_uuid": node.get("process_uuid"),
                    "port_id": port.get("id"),
                    "unit_group": port.get("unitGroup") or port.get("unit_group"),
                })
                return target
    return target


def _repair_target_for_process(graph_json: dict, process_uuid: str, repair_target: str = "node") -> dict:
    target = {"process_uuid": process_uuid, "repair_target": repair_target}
    needle = str(process_uuid or "").strip()
    for node in graph_json.get("nodes", []) or []:
        if not isinstance(node, dict):
            continue
        if str(node.get("process_uuid") or node.get("id") or "").strip() == needle:
            target["node_id"] = node.get("id")
            return target
    return target


def _enrich_readiness_issue_targets(graph_json: dict, issues: list[dict]) -> None:
    for issue in issues:
        details = issue.setdefault("details", {})
        if not isinstance(details, dict):
            continue
        context = issue.get("context")
        lookup = {**context, **details} if isinstance(context, dict) else details
        code = str(issue.get("code") or "")
        category = str(issue.get("category") or "")
        if code in {"MISSING_FLOWS", "missing_flow"}:
            details.setdefault("repair_target", "flow")
            missing = lookup.get("missing_flow_uuids")
            if isinstance(missing, list) and missing:
                details.update(_repair_target_for_flow_uuid(graph_json, str(missing[0])))
                details["missing_flow_uuids"] = missing
        elif (
            category == "tidas_placeholder"
            and "missing geography" in str(issue.get("message") or "").lower()
            and lookup.get("process_uuid")
        ):
            details.update(_repair_target_for_process(graph_json, str(lookup.get("process_uuid")), "process_metadata"))
        elif code in {"missing_tiangong_field"} and "geography" in str(issue.get("message") or "").lower():
            details.setdefault("repair_target", "project_settings")
        elif (
            category == "allocation"
            and "using first product output as reference" in str(issue.get("message") or "").lower()
            and lookup.get("process_uuid")
        ):
            details.update(_repair_target_for_process(graph_json, str(lookup.get("process_uuid")), "process_metadata"))
        elif category == "allocation" or code == "manual_allocation_required":
            process_uuid = str(lookup.get("process_uuid") or "")
            if process_uuid:
                details.update(_repair_target_for_process(graph_json, process_uuid, "allocation"))
            else:
                details.setdefault("repair_target", "allocation")
        elif code == "unsupported_unit_group" and lookup.get("unit_group"):
            details.update(_repair_target_for_unit_group(graph_json, str(lookup.get("unit_group"))))
        elif lookup.get("flow_uuid"):
            details.update(_repair_target_for_flow_uuid(graph_json, str(lookup.get("flow_uuid"))))
        elif lookup.get("process_uuid") or lookup.get("node_id"):
            details.setdefault("repair_target", "node")


def _identify_product_outputs(
    outputs: list,
    flow_type_map: dict[str, str] | None = None,
) -> list[dict]:
    """Identify product outputs from a process node's outputs.

    A product output is:
    - isProduct=True, OR
    - flow_type is "Product flow" or "waste_flow" (looked up by flowUuid)

    Args:
        outputs: List of output ports
        flow_type_map: Optional dict mapping flow_uuid -> flow_type

    Returns list of product output ports with their flow info.
    """
    product_outputs = []
    for port in outputs:
        if not isinstance(port, dict):
            continue
        
        # Check isProduct flag
        is_product = bool(port.get("isProduct", False))
        
        # Also check flow type from flowUuid lookup
        if not is_product and flow_type_map:
            flow_uuid = port.get("flowUuid")
            if flow_uuid:
                flow_type = flow_type_map.get(flow_uuid, "")
                is_product = flow_type in ("Product flow", "waste_flow")
        
        if is_product:
            product_outputs.append(port)
    
    return product_outputs


def _select_reference_flow(
    product_outputs: list[dict],
    process_uuid: str,
    model: Model | None,
    report: ExportReport,
    reference_product_flow_uuid: str | None = None,
    reference_product_name: str | None = None,
) -> tuple[dict | None, str | None]:
    """Select the reference (quantitative reference) flow for a process.

    Priority:
    1. User-specified reference_product (from Model)
    2. Single product output (automatic, allocation=1.0)
    3. Multi-product: choose first product output as fallback

    Returns:
        Tuple of (reference_port, reference_flow_uuid)
    """
    if not product_outputs:
        return None, None

    # Single product output - automatic reference
    if len(product_outputs) == 1:
        ref_port = product_outputs[0]
        ref_flow_uuid = ref_port.get("flowUuid")
        report.reference_flow_by_process[process_uuid] = ref_flow_uuid
        return ref_port, ref_flow_uuid

    # Multi-product process
    report.multi_product_process_count += 1

    explicit_uuid = str(reference_product_flow_uuid or "").strip()
    explicit_name = str(reference_product_name or "").strip()
    if explicit_uuid or explicit_name:
        for port in product_outputs:
            flow_uuid = str(port.get("flowUuid") or "").strip()
            port_id = str(port.get("id") or "").strip()
            port_name = str(port.get("name") or "").strip()
            if explicit_uuid and explicit_uuid in {flow_uuid, port_id}:
                ref_port = port
                ref_flow_uuid = port.get("flowUuid")
                report.reference_flow_by_process[process_uuid] = ref_flow_uuid
                return ref_port, ref_flow_uuid
            if explicit_name and port_name == explicit_name:
                ref_port = port
                ref_flow_uuid = port.get("flowUuid")
                report.reference_flow_by_process[process_uuid] = ref_flow_uuid
                return ref_port, ref_flow_uuid

    # Try to match model's reference_product
    if model and model.reference_product:
        for port in product_outputs:
            flow_uuid = port.get("flowUuid")
            # Match by flow UUID or flow name
            if flow_uuid == model.reference_product or port.get("name") == model.reference_product:
                ref_port = port
                ref_flow_uuid = flow_uuid
                report.reference_flow_by_process[process_uuid] = ref_flow_uuid
                return ref_port, ref_flow_uuid

    # Fallback: use first product output
    ref_port = product_outputs[0]
    ref_flow_uuid = ref_port.get("flowUuid")
    report.reference_flow_by_process[process_uuid] = ref_flow_uuid
    
    # Warn that we're using fallback
    report.add_warning(
        "allocation",
        f"Multi-product process {process_uuid}: using first product output as reference (no explicit reference_product specified)",
        {"process_uuid": process_uuid, "reference_flow_uuid": ref_flow_uuid},
    )
    
    return ref_port, ref_flow_uuid


def _calculate_allocation_factors(
    product_outputs: list[dict],
    reference_port: dict | None,
    process_uuid: str,
    report: ExportReport,
    db: Session | None = None,
) -> dict[str, float] | None:
    """Calculate allocation factors for multi-product process outputs.

    Allocation is based on physical relationships (output quantities) when products
    share the same unit group. For different unit groups, manual allocation is required.

    Args:
        product_outputs: List of product output ports
        reference_port: Selected reference flow port
        process_uuid: Process UUID for reporting
        report: ExportReport for warnings
        db: Optional DB session for unit conversion

    Returns:
        Dict mapping port_id -> allocation_factor (0.0 to 1.0)
    """
    unit_factor_by_group_and_name: dict[tuple[str, str], float] | None = None
    if db is not None:
        try:
            unit_factor_by_group_and_name = {
                (str(row.unit_group), str(row.unit_name)): float(row.factor_to_reference)
                for row in db.query(UnitDefinition).all()
            }
        except Exception:
            unit_factor_by_group_and_name = None

    result = calculate_product_allocation(
        product_outputs,
        process_uuid=process_uuid,
        unit_factor_by_group_and_name=unit_factor_by_group_and_name,
    )
    for warning in result.warnings:
        report.add_warning("allocation", warning.message, warning.context)
    if result.manual_required and process_uuid not in report.manual_allocation_required_processes:
        report.manual_allocation_required_processes.append(process_uuid)
    return result.factors


def _utc_timestamp() -> str:
    return datetime.utcnow().replace(microsecond=0).isoformat() + "Z"


def _lang_item(text: Any, lang: str) -> dict:
    value = str(text or "").strip()
    if not value:
        value = TIDAS_PLACEHOLDER_ZH if lang == "zh" else TIDAS_PLACEHOLDER_EN
    return {"#text": value, "@xml:lang": lang}


def _localized_items(zh: Any, en: Any | None = None) -> list[dict]:
    items = [_lang_item(zh, "zh")]
    en_text = str(en or "").strip()
    if en_text and en_text != str(zh or "").strip():
        items.append(_lang_item(en_text, "en"))
    return items


def _tidas_name(
    zh: Any,
    en: Any | None = None,
    *,
    mix_zh: Any | None = None,
    mix_en: Any | None = None,
    route_zh: Any | None = None,
    route_en: Any | None = None,
) -> dict:
    return {
        "baseName": _localized_items(zh, en),
        "mixAndLocationTypes": _localized_items(mix_zh or TIDAS_PLACEHOLDER_ZH, mix_en or TIDAS_PLACEHOLDER_EN),
        "treatmentStandardsRoutes": _localized_items(
            route_zh or TIDAS_ROUTE_PLACEHOLDER_ZH,
            route_en or TIDAS_ROUTE_PLACEHOLDER_EN,
        ),
    }


def _classification_information(label: Any | None, class_id: str = "0") -> dict:
    text = str(label or "").strip() or "Unclassified"
    return {
        "common:classification": {
            "common:class": [
                {
                    "#text": text,
                    "@classId": class_id,
                    "@level": "0",
                }
            ]
        }
    }


def _common_admin_information(dataset_version: str = TIDAS_DEFAULT_DATASET_VERSION) -> dict:
    return {
        "dataEntryBy": {
            "common:referenceToDataSetFormat": dict(TIDAS_DATASET_FORMAT_REF),
            "common:referenceToPersonOrEntityEnteringTheData": {},
            "common:timeStamp": _utc_timestamp(),
        },
        "publicationAndOwnership": {
            "common:dataSetVersion": dataset_version,
            "common:referenceToOwnershipOfDataSet": dict(TIDAS_OWNERSHIP_REF),
            "common:referenceToPrecedingDataSetVersion": {},
        },
    }


def _flow_root_attrs() -> dict:
    return {
        "@locations": "../ILCDLocations.xml",
        "@version": TIDAS_ILCD_SCHEMA_VERSION,
        "@xmlns": "http://lca.jrc.it/ILCD/Flow",
        "@xmlns:common": "http://lca.jrc.it/ILCD/Common",
        "@xmlns:ecn": "http://eplca.jrc.ec.europa.eu/ILCD/Extensions/2018/ECNumber",
        "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
        "@xsi:schemaLocation": "http://lca.jrc.it/ILCD/Flow ../../schemas/ILCD_FlowDataSet.xsd",
    }


def _process_root_attrs() -> dict:
    return {
        "@locations": "../ILCDLocations.xml",
        "@version": TIDAS_ILCD_SCHEMA_VERSION,
        "@xmlns": "http://lca.jrc.it/ILCD/Process",
        "@xmlns:common": "http://lca.jrc.it/ILCD/Common",
        "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
        "@xsi:schemaLocation": "http://lca.jrc.it/ILCD/Process ../../schemas/ILCD_ProcessDataSet.xsd",
    }


def _model_root_attrs() -> dict:
    return {
        "@locations": "../ILCDLocations.xml",
        "@version": TIDAS_ILCD_SCHEMA_VERSION,
        "@xmlns": "http://eplca.jrc.ec.europa.eu/ILCD/LifeCycleModel/2017",
        "@xmlns:acme": "http://acme.com/custom",
        "@xmlns:common": "http://lca.jrc.it/ILCD/Common",
        "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
        "@xsi:schemaLocation": (
            "http://eplca.jrc.ec.europa.eu/ILCD/LifeCycleModel/2017 "
            "../../schemas/ILCD_LifeCycleModelDataSet.xsd"
        ),
    }


def _flow_property_description(unit_group: str | None) -> list[dict]:
    label = str(unit_group or "").strip().lower()
    if "energy" in label or "能源" in label or "joule" in label:
        return [
            {"#text": "Energy", "@xml:lang": "en"},
            {"#text": "能量", "@xml:lang": "zh"},
        ]
    if "volume" in label or "体积" in label:
        return [
            {"#text": "Volume", "@xml:lang": "en"},
            {"#text": "体积", "@xml:lang": "zh"},
        ]
    if "item" in label or "unit" in label or "数量" in label:
        return [
            {"#text": "Number of items", "@xml:lang": "en"},
            {"#text": "数量", "@xml:lang": "zh"},
        ]
    return [
        {"#text": "Mass", "@xml:lang": "en"},
        {"#text": "质量", "@xml:lang": "zh"},
    ]


def _flow_property(flow_uuid: str, unit_group: str | None, report: ExportReport) -> dict:
    label = str(unit_group or "").strip()
    reference = get_tidas_flow_property_reference(label) if label else None
    if not label:
        report.add_warning(
            "tidas_placeholder",
            f"Flow {flow_uuid} missing unit_group; using generic Mass flow property placeholder",
            {"flow_uuid": flow_uuid},
        )
    elif reference:
        return {
            "flowProperty": {
                "@dataSetInternalID": "0",
                "meanValue": "1.0",
                "referenceToFlowPropertyDataSet": reference,
            }
        }
    elif "mass" not in label.lower() and "质量" not in label:
        report.add_warning(
            "tidas_placeholder",
            f"Flow {flow_uuid} uses unit group '{label}'; flow property reference is exported as a placeholder",
            {"flow_uuid": flow_uuid, "unit_group": label},
        )
    return {
        "flowProperty": {
            "@dataSetInternalID": "0",
            "meanValue": "1.0",
            "referenceToFlowPropertyDataSet": {
                "@refObjectId": "93a60a56-a3c8-11da-a746-0800200b9a66",
                "@type": "flow property data set",
                "@uri": "../flowproperties/93a60a56-a3c8-11da-a746-0800200b9a66.xml",
                "@version": "03.00.003",
                "common:shortDescription": _flow_property_description(unit_group),
            },
        }
    }


def _flow_type_for_tidas(flow_type: str | None) -> str:
    ft = (flow_type or "").replace("_", " ").strip().lower()
    if ft == "elementary flow":
        return "Elementary flow"
    if ft == "waste flow":
        return "Waste flow"
    return "Product flow"


def _common_modelling_and_validation(type_of_dataset: str) -> dict:
    return {
        "LCIMethod": {
            "typeOfDataSet": type_of_dataset,
        },
        "complianceDeclarations": {
            "compliance": {
                "common:approvalOfOverallCompliance": "Fully compliant",
                "common:referenceToComplianceSystem": dict(TIDAS_COMPLIANCE_REF),
            }
        },
    }


def _process_modelling_and_validation() -> dict:
    return {
        "LCIMethodAndAllocation": {
            "typeOfDataSet": "Unit process, single operation",
        },
        "completeness": {
            "completenessElementaryFlows": {},
        },
        "dataSourcesTreatmentAndRepresentativeness": {
            "dataCutOffAndCompletenessPrinciples": _localized_items(TIDAS_GENERATED_COMMENT, TIDAS_GENERATED_COMMENT),
            "referenceToDataSource": {},
        },
    }


def _location_value(location: Any | None, report: ExportReport, context: dict, label: str) -> str:
    value = str(location or "").strip()
    if value:
        return value
    report.add_warning("tidas_placeholder", f"{label} missing geography; using GLO", context)
    return "GLO"


def _reference_year_value(value: Any | None, report: ExportReport, context: dict, label: str) -> int:
    if value is None or value == "":
        return TIDAS_DEFAULT_YEAR
    try:
        year = int(value)
    except (TypeError, ValueError):
        report.add_warning("tidas_placeholder", f"{label} invalid reference year; using {TIDAS_DEFAULT_YEAR}", context)
        return TIDAS_DEFAULT_YEAR
    if 1000 <= year <= 9999:
        return year
    report.add_warning("tidas_placeholder", f"{label} invalid reference year; using {TIDAS_DEFAULT_YEAR}", context)
    return TIDAS_DEFAULT_YEAR


def _reference_to_flow(flow_uuid: Any, description: Any | None = None) -> dict:
    return {
        "@refObjectId": str(flow_uuid or ""),
        "@type": "flow data set",
        "@uri": f"../flows/{flow_uuid}.xml",
        "@version": TIDAS_DEFAULT_DATASET_VERSION,
        "common:shortDescription": _localized_items(description or flow_uuid, description or flow_uuid),
    }


def _reference_to_process(process_uuid: Any, description: Any | None = None) -> dict:
    return {
        "@refObjectId": _tidas_uuid(process_uuid),
        "@type": "process data set",
        "@uri": f"../processes/{_tidas_uuid(process_uuid)}.xml",
        "@version": TIDAS_DEFAULT_DATASET_VERSION,
        "common:shortDescription": _localized_items(description or process_uuid, description or process_uuid),
    }


def _tidas_uuid(value: Any) -> str:
    text = str(value or "").strip()
    try:
        return str(uuid.UUID(text))
    except (TypeError, ValueError, AttributeError):
        return str(uuid.uuid5(uuid.NAMESPACE_URL, f"nebula-lca:tidas:{text}"))


def _exchange_direction(value: str | None) -> str:
    return "Output" if str(value or "").strip().lower() == "output" else "Input"


def _exchange_amount(value: Any) -> Any:
    return value if value is not None else 0


def _build_tidas_exchange(exc: dict, allocation_factors: dict | None = None, ref_internal_id: str | None = None) -> dict:
    internal_id = str(exc.get("internal_id") or exc.get("@dataSetInternalID") or "0")
    flow_uuid = exc.get("flow_uuid") or exc.get("flowUuid") or exc.get("@flowUUID") or ""
    direction = _exchange_direction(exc.get("direction"))
    raw_amount = exc.get("amount") if "amount" in exc else exc.get("meanAmount")
    amount = 1 if raw_amount is None and direction == "Output" and internal_id == ref_internal_id else _exchange_amount(raw_amount)
    tidas_exc = {
        "@dataSetInternalID": internal_id,
        "referenceToFlowDataSet": _reference_to_flow(flow_uuid, exc.get("port_name") or exc.get("name") or flow_uuid),
        "exchangeDirection": direction,
        "meanAmount": amount,
        "resultingAmount": amount,
        "dataDerivationTypeStatus": "Calculated",
        "referencesToDataSource": {"referenceToDataSource": {}},
        "allocations": {"allocation": {}},
    }
    if direction == "Output" and allocation_factors is not None:
        factor = allocation_factors.get(internal_id)
        if factor is not None:
            tidas_exc["allocations"] = {
                "allocation": {
                    "@allocatedFraction": f"{factor * 100:g}%",
                }
            }
            tidas_exc["json_tg_allocation"] = {
                "allocationFactor": factor,
                "isReferenceFlow": internal_id == ref_internal_id,
            }
    elif direction == "Output" and ref_internal_id:
        tidas_exc["json_tg_allocation"] = {
            "manualAllocationRequired": True,
            "isReferenceFlow": internal_id == ref_internal_id,
        }
    return tidas_exc


def _build_flow_data(db: Session, flow_uuid: str, report: ExportReport) -> dict | None:
    """Build a TIDAS/ILCD-style flowDataSet for a single flow.

    Returns None if flow not found (will be reported as error).
    """
    flow_record = db.get(FlowRecord, flow_uuid)

    if flow_record is None:
        report.add_error(f"Flow not found: {flow_uuid}")
        return None

    category_label = flow_record.compartment or getattr(flow_record, "category", None) or "Unclassified"
    dsi = {
        "common:UUID": flow_record.flow_uuid,
        "name": _tidas_name(flow_record.flow_name, flow_record.flow_name_en),
        "classificationInformation": _classification_information(category_label),
        "common:generalComment": _localized_items(TIDAS_GENERATED_COMMENT, TIDAS_GENERATED_COMMENT),
        "common:other": {},
        "common:synonyms": {},
    }

    if flow_record.source_updated_at:
        dsi["common:timeStamp"] = flow_record.source_updated_at

    flow_dataset = {
        **_flow_root_attrs(),
        "administrativeInformation": _common_admin_information(),
        "flowInformation": {
            "dataSetInformation": dsi,
            "quantitativeReference": {
                "referenceToReferenceFlowProperty": "0",
            },
        },
        "flowProperties": _flow_property(flow_uuid, flow_record.unit_group, report),
        "modellingAndValidation": _common_modelling_and_validation(_flow_type_for_tidas(flow_record.flow_type)),
    }

    # Nebula-compatible fallback fields consumed by our importer.
    if flow_record.default_unit:
        flow_dataset["flowInformation"]["referenceUnit"] = flow_record.default_unit
    if flow_record.unit_group:
        flow_dataset["flowInformation"]["unitGroup"] = flow_record.unit_group
    flow_dataset["flowInformation"]["flowType"] = _flow_type_for_tidas(flow_record.flow_type)
    if flow_record.compartment:
        flow_dataset["flowInformation"]["compartment"] = flow_record.compartment

    if not flow_record.compartment:
        report.add_warning(
            "tidas_placeholder",
            f"Flow {flow_uuid} missing compartment/category; using Unclassified",
            {"flow_uuid": flow_uuid},
        )

    report.flow_count += 1
    return {"flowDataSet": flow_dataset}


def _build_process_data(
    db: Session, process_uuid: str, graph_json: dict, report: ExportReport, model: Model | None = None, flow_type_map: dict[str, str] | None = None
) -> dict | None:
    """Build a TIDAS/ILCD-style processDataSet for a single process."""
    ref_process = db.get(ReferenceProcess, process_uuid)

    if ref_process is not None and ref_process.process_json:
        existing = ref_process.process_json
        if "processDataSet" in existing and isinstance(existing["processDataSet"], dict):
            existing_root = existing["processDataSet"]
            if existing_root.get("@xmlns") and existing_root.get("administrativeInformation"):
                report.process_count += 1
                return existing
            pi = dict(existing_root)
        else:
            pi = dict(existing)

        process_name = pi.get("process_name_zh") or pi.get("process_name") or pi.get("name") or process_uuid
        process_name_en = pi.get("process_name_en")
        location = pi.get("location") or pi.get("geography") or (model.geography if model else None)
        reference_year = pi.get("reference_year")
        time_representativeness = pi.get("time_representativeness") or (model.time_representativeness if model else None)
        technology_description = pi.get("technology_description") or TIDAS_GENERATED_COMMENT
        process_reference_product = pi.get("reference_product")
        process_reference_product_flow_uuid = pi.get("reference_product_flow_uuid")
        exchanges = pi.get("exchanges") if isinstance(pi.get("exchanges"), list) else []
        ref_internal_id = str(pi.get("reference_flow_internal_id") or "")
        ref_flow_uuid = pi.get("reference_flow_source_uuid")
        allocation_source_ports = [
            {
                "id": str(exc.get("internal_id") or "0"),
                "flowUuid": exc.get("flow_uuid"),
                "name": exc.get("port_name") or exc.get("name") or exc.get("flow_name"),
                "unit": exc.get("unit"),
                "unitGroup": exc.get("unit_group"),
                "amount": exc.get("amount"),
                "isProduct": exc.get("direction") == "output",
                "allocationFactor": exc.get("allocationFactor"),
                "allocationBasis": exc.get("allocationBasis") or exc.get("allocation_basis"),
            }
            for exc in exchanges
            if exc.get("direction") == "output"
        ]
    else:
        graph = HybridGraph.model_validate(graph_json)
        node_data = None
        for node in graph.nodes:
            if node.process_uuid == process_uuid or node.id == process_uuid:
                node_data = node
                break

        if node_data is None:
            report.add_error(f"Process node not found in graph: {process_uuid}")
            return None

        process_name = node_data.name
        process_name_en = None
        location = node_data.location or (model.geography if model else None)
        reference_year = node_data.reference_year
        time_representativeness = node_data.time_representativeness or (model.time_representativeness if model else None)
        technology_description = node_data.technology_description or TIDAS_GENERATED_COMMENT
        process_reference_product = node_data.reference_product
        process_reference_product_flow_uuid = node_data.reference_product_flow_uuid
        exchanges = []
        unit_factor_by_group_and_name, reference_unit_by_group = build_unit_reference_maps(db)

        def _port_exchange(port: Any, direction: str) -> dict:
            semantics = resolve_flow_port_unit_semantics(
                db,
                port,
                unit_factor_by_group_and_name=unit_factor_by_group_and_name,
                reference_unit_by_group=reference_unit_by_group,
            )
            if not semantics.ok:
                report.add_error(
                    f"Flow {semantics.flow_uuid} cannot be converted back to its default unit for TIDAS export: {semantics.reason}"
                )
            unit_group_switch = dict(semantics.unit_group_switch or {})
            unit_group_switch.pop("sourceAmount", None)
            unit_group_switch.pop("source_amount", None)
            unit_group_switch.pop("sourceExternalSaleAmount", None)
            unit_group_switch.pop("source_external_sale_amount", None)
            return {
                "internal_id": port.id,
                "flow_uuid": port.flowUuid,
                "direction": direction,
                "port_name": port.name,
                "amount": semantics.amount_in_flow_default_unit if semantics.ok else port.amount,
                "unit": semantics.flow_default_unit or port.unit,
                "unit_group": semantics.flow_default_unit_group or port.unitGroup,
                "current_amount": port.amount,
                "current_unit": semantics.current_unit,
                "current_unit_group": semantics.current_unit_group,
                "unit_group_switch": unit_group_switch,
            }

        for port in node_data.inputs:
            exchanges.append(_port_exchange(port, "input"))
        for port in node_data.outputs:
            output_exchange = _port_exchange(port, "output")
            output_exchange["allocationFactor"] = port.allocationFactor
            output_exchange["allocationBasis"] = port.allocationBasis
            exchanges.append(output_exchange)

        allocation_source_ports = [p.model_dump() if hasattr(p, "model_dump") else p for p in node_data.outputs]

        product_outputs = _identify_product_outputs(
            allocation_source_ports,
            flow_type_map,
        )
        ref_port, ref_flow_uuid = _select_reference_flow(
            product_outputs,
            process_uuid,
            model,
            report,
            process_reference_product_flow_uuid,
            process_reference_product,
        )
        ref_internal_id = str(ref_port.get("id") if ref_port else "")

    if not ref_internal_id:
        reference_candidates = _identify_product_outputs(allocation_source_ports, flow_type_map)
        ref_port, ref_flow_uuid = _select_reference_flow(
            reference_candidates,
            process_uuid,
            model,
            report,
            process_reference_product_flow_uuid,
            process_reference_product,
        )
        ref_internal_id = str(ref_port.get("id") if ref_port else "")
    if not ref_internal_id:
        for exc in exchanges:
            if exc.get("direction") == "output":
                ref_internal_id = str(exc.get("internal_id") or "0")
                ref_flow_uuid = ref_flow_uuid or exc.get("flow_uuid")
                break
    if not ref_internal_id:
        ref_internal_id = "0"
    reference_exchange = next(
        (exc for exc in exchanges if str(exc.get("internal_id") or "0") == ref_internal_id),
        None,
    )

    product_outputs = _identify_product_outputs(allocation_source_ports, flow_type_map)
    allocation_factors = _calculate_allocation_factors(product_outputs, None, process_uuid, report, db) if product_outputs else {}

    tidas_location = _location_value(
        location,
        report,
        {"process_uuid": process_uuid},
        f"Process {process_uuid}",
    )
    tidas_reference_year = _reference_year_value(
        reference_year,
        report,
        {"process_uuid": process_uuid},
        f"Process {process_uuid}",
    )
    time_block = {"common:referenceYear": tidas_reference_year}
    if str(time_representativeness or "").strip():
        time_block["common:timeRepresentativenessDescription"] = _localized_items(
            time_representativeness,
            time_representativeness,
        )
    technology_text = str(technology_description or "").strip() or TIDAS_GENERATED_COMMENT
    process_dataset = {
        **_process_root_attrs(),
        "administrativeInformation": {
            "common:commissionerAndGoal": {
                "common:intendedApplications": _localized_items(TIDAS_GENERATED_COMMENT, TIDAS_GENERATED_COMMENT),
                "common:referenceToCommissioner": dict(TIDAS_OWNERSHIP_REF),
            },
            **_common_admin_information(),
        },
        "processInformation": {
            "dataSetInformation": {
                "common:UUID": _tidas_uuid(process_uuid),
                "name": _tidas_name(process_name, process_name_en),
                "classificationInformation": _classification_information("Unclassified"),
                "common:generalComment": _localized_items(TIDAS_GENERATED_COMMENT, TIDAS_GENERATED_COMMENT),
            },
            "time": time_block,
            "geography": {"locationOfOperationSupplyOrProduction": {"@location": tidas_location}},
            "technology": {
                "technologyDescriptionAndIncludedProcesses": _localized_items(
                    technology_text,
                    technology_text,
                ),
                "referenceToTechnologyFlowDiagrammOrPicture": {},
            },
            "mathematicalRelations": {"variableParameter": {}},
            "quantitativeReference": {
                "@type": "Reference flow(s)",
                "referenceToReferenceFlow": ref_internal_id,
            },
        },
        "exchanges": {
            "exchange": [
                _build_tidas_exchange(exc, allocation_factors, ref_internal_id)
                for exc in exchanges
            ]
        },
        "modellingAndValidation": _process_modelling_and_validation(),
    }

    report.process_count += 1
    return {
        "processDataSet": process_dataset,
        "json_tg": {
            "process_uuid": process_uuid,
            "process_name": process_name,
            "reference_flow_internal_id": ref_internal_id,
            "reference_flow_source_uuid": ref_flow_uuid,
            "reference_quantity": {
                "amount": (
                    reference_exchange.get("amount")
                    if reference_exchange and reference_exchange.get("amount") is not None
                    else 1
                ),
                "unit": reference_exchange.get("unit") if reference_exchange else None,
            },
            "exchanges": exchanges,
        },
    }


def _build_model_data(
    db: Session, model: Model, graph_json: dict, report: ExportReport
) -> dict:
    """Build lifeCycleModelDataSet from Model and graph.

    Exports in TIDAS/ILCD format with Nebula extension fields:
    - lifeCycleModelDataSet: standard ILCD structure
    - json_tg.xflow: Nebula graph extension
    - xflow_nodes/xflow_edges/process_instances: for _build_tidas_graph_from_model_record
    """
    # Extract process refs from graph
    _, process_uuids = _extract_graph_data(graph_json)

    # Extract xflow nodes and edges for reconstruction
    xflow_nodes = graph_json.get("nodes", [])
    xflow_edges = graph_json.get("exchanges", [])

    # Build process instances from nodes
    process_instances = []
    for idx, node in enumerate(xflow_nodes):
        if not isinstance(node, dict):
            continue
        process_uuid = node.get("process_uuid") or node.get("id")
        if not process_uuid:
            continue
        process_instances.append({
            "internal_id": str(idx),
            "process_uuid": str(process_uuid),
        })

    geography = _location_value(
        model.geography,
        report,
        {"model_uuid": model.id},
        f"Model {model.id}",
    )
    process_instance_items = []
    for instance in process_instances:
        process_uuid = instance["process_uuid"]
        process_instance_items.append({
            "@dataSetInternalID": instance["internal_id"],
            "@multiplicationFactor": "1",
            "connections": {},
            "referenceToProcess": _reference_to_process(process_uuid, process_uuid),
        })

    model_dataset = {
        **_model_root_attrs(),
        "administrativeInformation": {
            "common:commissionerAndGoal": {
                "common:intendedApplications": _localized_items(TIDAS_GENERATED_COMMENT, TIDAS_GENERATED_COMMENT),
                "common:referenceToCommissioner": dict(TIDAS_OWNERSHIP_REF),
            },
            **_common_admin_information(),
        },
        "lifeCycleModelInformation": {
            "dataSetInformation": {
                "common:UUID": _tidas_uuid(model.id),
                "name": _tidas_name(model.name, model.name),
                "classificationInformation": _classification_information("Unclassified"),
                "common:generalComment": _localized_items(
                    model.description or TIDAS_GENERATED_COMMENT,
                    model.description or TIDAS_GENERATED_COMMENT,
                ),
                "referenceToExternalDocumentation": {},
                "referenceToResultingProcess": {},
                "json_tg": {
                    "xflow": graph_json,
                    "project_metadata": {
                        "reference_product": model.reference_product,
                        "functional_unit": model.functional_unit,
                        "system_boundary": model.system_boundary,
                        "time_representativeness": model.time_representativeness,
                        "geography": model.geography,
                    },
                },
            },
            "quantitativeReference": {
                "referenceToReferenceProcess": process_instances[0]["internal_id"] if process_instances else "0",
            },
            "technology": {
                "processes": {
                    "processInstance": process_instance_items,
                },
                "referenceToDiagram": {},
            },
            "geography": {"locationOfOperationSupplyOrProduction": {"@location": geography}},
        },
        "modellingAndValidation": {
            "dataSourcesTreatmentEtc": {},
        },
    }

    # Build combined model data with both ILCD and Nebula fields
    model_data = {
        # Simplified fields for quick Nebula import
        "model_uuid": model.id,
        "model_name": model.name,
        "reference_product": model.reference_product,
        "functional_unit": model.functional_unit,
        "system_boundary": model.system_boundary,
        "time_representativeness": model.time_representativeness,
        "geography": model.geography,
        "description": model.description,
        "process_refs": list(process_uuids),
        # ILCD root structure (with json_tg extension inside)
        "lifeCycleModelDataSet": model_dataset,
        # Nebula graph extensions for _build_tidas_graph_from_model_record
        "xflow_nodes": xflow_nodes,
        "xflow_edges": xflow_edges,
        "process_instances": process_instances,
        # Legacy flat json_tg.xflow for compatibility
        "json_tg": {"xflow": graph_json},
    }

    # Check for missing TianGong fields (warnings only)
    if not model.reference_product:
        report.add_warning(
            "missing_tiangong_field",
            f"Model {model.id} missing reference_product",
            {"model_uuid": model.id},
        )
    if not model.functional_unit:
        report.add_warning(
            "missing_tiangong_field",
            f"Model {model.id} missing functional_unit",
            {"model_uuid": model.id},
        )
    if not model.geography:
        report.add_warning(
            "missing_tiangong_field",
            f"Model {model.id} missing geography",
            {"model_uuid": model.id},
        )

    report.exported_model_count += 1
    return model_data


def _build_manifest(
    model_uuid: str,
    flow_uuids: list[str],
    process_uuids: list[str],
) -> dict:
    """Build v2 manifest.json for TIDAS bundle.

    Entries point to actual per-dataset files in ZIP.
    """
    version = TIDAS_DEFAULT_DATASET_VERSION
    entries = [
        {
            "table": "lifecyclemodels",
            "id": model_uuid,
            "version": version,
            "file_path": f"lifecyclemodels/{model_uuid}_{version}.json",
            "rule_verification": True,
        }
    ]
    entries.extend(
        {
            "table": "flows",
            "id": flow_uuid,
            "version": version,
            "file_path": f"flows/{flow_uuid}_{version}.json",
            "rule_verification": True,
        }
        for flow_uuid in flow_uuids
    )
    entries.extend(
        {
            "table": "processes",
            "id": _tidas_uuid(process_uuid),
            "version": version,
            "file_path": f"processes/{_tidas_uuid(process_uuid)}_{version}.json",
            "rule_verification": True,
        }
        for process_uuid in process_uuids
    )

    return {
        "format": "tiangong-tidas-package",
        "version": 2,
        "exported_at": datetime.utcnow().isoformat(),
        "scope": "selected_roots",
        "roots": [
            {
                "table": "lifecyclemodels",
                "id": model_uuid,
                "version": version,
            }
        ],
        "entries": entries,
        "counts": {
            "lifecyclemodels": 1,
            "flows": len(flow_uuids),
            "processes": len(process_uuids),
        },
        "total_count": len(entries),
    }


def build_tidas_readiness(
    db: Session, project_id: str, version: int | None = None
) -> dict[str, Any]:
    """Build TIDAS export readiness report.

    This is the single shared readiness builder called by both
    ``preview_export()`` and ``export_bundle()``.

    Returns a dict with:
        - can_export: bool
        - source_policy: str
        - blocking: list[dict]   (blocking issues)
        - warnings: list[dict]   (non-blocking warnings)
        - info: list[dict]       (informational summary)
        - flow_count, process_count, exported_model_count
        - multi_product_process_count
        - allocation_warnings, manual_allocation_required_processes
        - reference_flow_by_process
        - missing_flows, missing_processes

    Blocking rules:
        - no model version / empty graph
        - PTS nodes
        - missing flows / missing processes
        - unsupported elementary source-space for TIDAS export
        - validate_project_source_policy() errors when project policy is tidas_compliant
        - unsupported unit groups (e.g. kg*km, sej) in TIDAS compliant projects

    Warnings:
        - existing exporter warnings (geography fallback, allocation warnings)
        - open-mixed source warnings and unknown-source warnings

    Info:
        - project source policy
        - source mix summary
        - TIDAS reference seed status/version
    """
    blocking: list[dict] = []
    warnings: list[dict] = []
    info: list[dict] = []

    # ── Fetch model and version ────────────────────────────────────────
    model = db.get(Model, project_id)
    if model is None:
        blocking.append({
            "code": "PROJECT_NOT_FOUND",
            "message": f"Project {project_id} not found",
        })
        return _readiness_result(blocking, warnings, info, model)

    source_policy = str(model.source_policy or "open_mixed")
    info.append({
        "code": "source_policy",
        "message": f"Source policy: {source_policy}",
        "details": {"source_policy": source_policy},
    })

    # ── Fetch model version ────────────────────────────────────────────
    model_version = _get_model_version(db, project_id, version)
    if model_version is None:
        version_info = f" version {version}" if version else ""
        blocking.append({
            "code": "NO_MODEL_VERSION",
            "message": f"No model version found for project {project_id}{version_info}",
        })
        return _readiness_result(blocking, warnings, info, model)

    # ── Empty graph check ──────────────────────────────────────────────
    graph_json = model_version.hybrid_graph_json
    if not graph_json:
        blocking.append({
            "code": "EMPTY_GRAPH",
            "message": f"Empty graph for project {project_id}",
        })
        return _readiness_result(blocking, warnings, info, model)

    # ── PTS node check ─────────────────────────────────────────────────
    pts_nodes = _find_pts_nodes(graph_json)
    if pts_nodes:
        pts_refs = [
            str(n.get("process_uuid") or n.get("pts_uuid") or n.get("id") or "").strip()
            for n in pts_nodes
        ]
        pts_refs = [r for r in pts_refs if r]
        blocking.append({
            "code": PTS_TIDAS_EXPORT_ERROR_CODE,
            "message": f"{PTS_TIDAS_EXPORT_MESSAGE} PTS nodes: {', '.join(pts_refs[:5])}",
            "details": {"pts_nodes": pts_refs},
        })
        return _readiness_result(blocking, warnings, info, model)

    # ── Extract graph data ─────────────────────────────────────────────
    flow_uuids, process_uuids = _extract_graph_data(graph_json)

    # ── Source-space check (elementary flows only) ─────────────────────
    _scan_source_space(db, flow_uuids, _report_as_readiness(blocking, warnings))

    # ── Flow validation ────────────────────────────────────────────────
    missing_flows: list[str] = []
    for flow_uuid in flow_uuids:
        flow_record = db.get(FlowRecord, flow_uuid)
        if flow_record is None:
            missing_flows.append(flow_uuid)

    if missing_flows:
        blocking.append({
            "code": "MISSING_FLOWS",
            "message": f"{len(missing_flows)} flow(s) not found in database",
            "details": {"missing_flow_uuids": missing_flows},
        })
        _enrich_readiness_issue_targets(graph_json, blocking)

    # ── Process validation ─────────────────────────────────────────────
    missing_processes: list[str] = []
    for process_uuid in process_uuids:
        ref_process = db.get(ReferenceProcess, process_uuid)
        if ref_process is None:
            node_found = any(
                isinstance(node, dict)
                and (node.get("process_uuid") or node.get("id")) == process_uuid
                for node in graph_json.get("nodes", [])
            )
            if not node_found:
                missing_processes.append(process_uuid)

    if missing_processes:
        blocking.append({
            "code": "MISSING_PROCESSES",
            "message": f"{len(missing_processes)} process(es) not found",
            "details": {"missing_process_uuids": missing_processes},
        })

    # ── Flow default-unit conversion validation ────────────────────────
    for violation in collect_flow_default_unit_conversion_violations(graph_json, db):
        blocking.append({
            "code": "FLOW_DEFAULT_UNIT_CONVERSION_REQUIRED",
            "message": "Flow current modelling unit cannot be converted back to the flow default unit for TIDAS export.",
            "details": violation,
        })

    # ── Source-policy validation ───────────────────────────────────────
    policy_result = _validate_project_source_policy_readiness(model, graph_json, source_policy, db)
    _enrich_readiness_issue_targets(graph_json, policy_result.errors)
    _enrich_readiness_issue_targets(graph_json, policy_result.warnings)
    for err in policy_result.errors:
        blocking.append(err)
    for warn in policy_result.warnings:
        warnings.append(warn)
    for inf in policy_result.info:
        info.append(inf)

    # ── Dry-run build to collect structural warnings ───────────────────
    flow_type_map = _build_flow_type_map(db, flow_uuids)
    export_report = ExportReport()

    for flow_uuid in sorted(flow_uuids):
        _build_flow_data(db, flow_uuid, export_report)
    for process_uuid in sorted(process_uuids):
        _build_process_data(db, process_uuid, graph_json, export_report, model, flow_type_map)
    _build_model_data(db, model, graph_json, export_report)

    # Merge structural warnings
    for w in export_report.warnings:
        wd = w.to_dict()
        if wd not in warnings:
            warnings.append(wd)
    _enrich_readiness_issue_targets(graph_json, warnings)
    allocation_warnings = [w.to_dict() for w in export_report.allocation_warnings]
    _enrich_readiness_issue_targets(graph_json, allocation_warnings)

    for violation in collect_multi_product_unit_group_violations(graph_json):
        blocking.append({
            "code": "MULTI_PRODUCT_UNIT_GROUP_MISMATCH",
            "message": "Multi-product process has products in different current unit groups; switch unit groups before export.",
            "details": {
                **violation,
                "repair_target": "allocation",
            },
        })

    # ── Source policy info ─────────────────────────────────────────────
    biosphere_uuids = _collect_biosphere_flow_uuids(graph_json)
    sources_by_uuid = _batch_lookup_flow_sources(db, biosphere_uuids)
    source_counts: dict[str, int] = {}
    for uuid_val, source in sources_by_uuid.items():
        space = classify_flow_source(source)
        source_counts[space] = source_counts.get(space, 0) + 1

    if source_counts:
        info.append({
            "code": "source_mix_summary",
            "message": f"Source distribution: {source_counts}",
            "details": {"source_distribution": source_counts},
        })

    # ── Seed status info ───────────────────────────────────────────────
    try:
        seed = load_tidas_reference_seed()
        pkg_version = seed.get("source_package_version", "")
        fp_count = len(seed.get("flow_properties") or [])
        mapping_count = len(seed.get("unit_group_mappings") or [])
        missing_fp_count = len(seed.get("missing_flow_property_mappings") or [])
        info.append({
            "code": "tidas_seed_status",
            "message": f"Reference seed: {pkg_version}",
            "details": {
                "flow_properties": fp_count,
                "unit_group_mappings": mapping_count,
                "missing_flow_property_mappings": missing_fp_count,
            },
        })
    except Exception:
        info.append({
            "code": "tidas_seed_status",
            "message": "No TIDAS reference seed loaded",
            "details": {},
        })

    can_export = not blocking and not (
        source_policy == "tidas_compliant"
        and policy_result.errors
    )

    return {
        "can_export": can_export,
        "source_policy": source_policy,
        "blocking": blocking,
        "warnings": warnings,
        "info": info,
        "flow_count": export_report.flow_count,
        "process_count": export_report.process_count,
        "exported_model_count": export_report.exported_model_count,
        "multi_product_process_count": export_report.multi_product_process_count,
        "allocation_warnings": allocation_warnings,
        "manual_allocation_required_processes": export_report.manual_allocation_required_processes,
        "reference_flow_by_process": export_report.reference_flow_by_process,
        "missing_flows": missing_flows,
        "missing_processes": missing_processes,
    }


def _readiness_result(
    blocking: list[dict],
    warnings: list[dict],
    info: list[dict],
    model: Model | None,
) -> dict[str, Any]:
    """Build a minimal readiness result when an early block occurs."""
    return {
        "can_export": not blocking,
        "source_policy": str(model.source_policy or "open_mixed") if model else "open_mixed",
        "blocking": blocking,
        "warnings": warnings,
        "info": info,
        "flow_count": 0,
        "process_count": 0,
        "exported_model_count": 0,
        "multi_product_process_count": 0,
        "allocation_warnings": [],
        "manual_allocation_required_processes": [],
        "reference_flow_by_process": {},
        "missing_flows": [],
        "missing_processes": [],
    }


class _report_as_readiness:
    """Thin ExportReport substitute that writes blocking/warnings into lists."""

    def __init__(self, blocking_list: list[dict], warnings_list: list[dict]):
        self._blocking = blocking_list
        self._warnings = warnings_list
        self.flow_count = 0
        self.process_count = 0
        self.exported_model_count = 0
        self.multi_product_process_count = 0
        self.allocation_warnings: list[ExportWarning] = []
        self.manual_allocation_required_processes: list[str] = []
        self.reference_flow_by_process: dict[str, str] = {}

    def add_error(self, message: str):
        code = "UNSPECIFIED_BLOCK"
        if "ecoinvent" in message.lower():
            code = "SOURCE_SPACE_ECOSPREAD_BLOCKED"
        elif "source" in message.lower():
            code = "SOURCE_SPACE_UNKNOWN_BLOCKED"
        self._blocking.append({"code": code, "message": message})

    def add_warning(self, category: str, message: str, context: dict | None = None):
        self._warnings.append({
            "category": category,
            "message": message,
            "context": context or {},
        })

    def has_errors(self) -> bool:
        return len(self._blocking) > 0


def _validate_project_source_policy_readiness(
    model: Model,
    graph: dict,
    source_policy: str,
    db: Session,
) -> "ValidationResult":
    """Run source-policy validation and return ValidationResult.

    This wraps validate_project_source_policy to catch errors that are
    already in blocking/warning format.
    """
    from app.source_policy import validate_project_source_policy

    try:
        return validate_project_source_policy(
            model_id=model.id,
            graph=graph,
            db=db,
            source_policy=source_policy,
        )
    except HTTPException as exc:
        result = _empty_result()
        for e in exc.detail.get("evidence", {}).get("errors", []):
            result.errors.append(e)
        return result


def _empty_result():
    """Return an empty ValidationResult for error handling."""
    from app.source_policy import ValidationResult
    return ValidationResult()


def preview_export(
    db: Session, project_id: str, version: int | None = None
) -> dict[str, Any]:
    """Preview export without generating ZIP.

    Delegates to ``build_tidas_readiness()`` and returns the same shape
    for compatibility (can_export, flow_count, process_count, etc.).
    """
    readiness = build_tidas_readiness(db, project_id, version)

    # Map readiness fields back to the existing preview shape for compatibility
    errors_as_strings = [e["message"] for e in readiness.get("blocking", [])]
    return {
        "can_export": readiness["can_export"],
        "flow_count": readiness["flow_count"],
        "process_count": readiness["process_count"],
        "exported_model_count": readiness["exported_model_count"],
        "multi_product_process_count": readiness["multi_product_process_count"],
        "allocation_warnings": readiness.get("allocation_warnings", []),
        "manual_allocation_required_processes": readiness.get("manual_allocation_required_processes", []),
        "reference_flow_by_process": readiness.get("reference_flow_by_process", {}),
        "warnings": readiness.get("warnings", []),
        "errors": errors_as_strings,
        "missing_flows": readiness.get("missing_flows", []),
        "missing_processes": readiness.get("missing_processes", []),
    }


def export_bundle(
    db: Session,
    project_id: str,
    version: int | None = None,
    display_lang: str = "zh",
) -> tuple[bytes, ExportReport]:
    """Export project to TIDAS bundle ZIP.

    Runs readiness check first; raises ``ExportError`` if blocking
    issues are found.  On success, reuses the same ZIP-build logic.

    Args:
        db: Database session
        project_id: Project/model ID
        version: Optional version number (None = latest)
        display_lang: Display language preference (zh/en)

    Returns:
        Tuple of (ZIP bytes, export report)

    Raises:
        ExportError: If validation fails
    """
    report = ExportReport()

    # ── Readiness check (short-circuit if blocking) ────────────────────
    readiness = build_tidas_readiness(db, project_id, version)
    if readiness["blocking"]:
        raise ExportError(readiness["blocking"][0]["message"])

    # ── Re-fetch model and version for ZIP build ───────────────────────
    model = db.get(Model, project_id)
    if model is None:
        raise ExportError(f"Project not found: {project_id}")

    model_version = _get_model_version(db, project_id, version)
    if model_version is None:
        version_info = f" version {version}" if version else ""
        raise ExportError(f"No model version found for project {project_id}{version_info}")

    graph_json = model_version.hybrid_graph_json
    if not graph_json:
        raise ExportError(f"Empty graph for project {project_id}")

    # ── Extract graph data ─────────────────────────────────────────────
    flow_uuids, process_uuids = _extract_graph_data(graph_json)

    # ── Validate flows ─────────────────────────────────────────────────
    missing_flows: list[str] = []
    for flow_uuid in flow_uuids:
        flow_record = db.get(FlowRecord, flow_uuid)
        if flow_record is None:
            missing_flows.append(flow_uuid)
            report.add_error(f"Missing flow: {flow_uuid}")

    if missing_flows:
        raise ExportError(f"Cannot export: {len(missing_flows)} flow(s) not found in database")

    # ── Build flow type map ────────────────────────────────────────────
    flow_type_map = _build_flow_type_map(db, flow_uuids)

    # ── Build ZIP in memory ────────────────────────────────────────────
    zip_buffer = io.BytesIO()

    with zipfile.ZipFile(zip_buffer, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        dataset_version = TIDAS_DEFAULT_DATASET_VERSION

        # Build and write flow data as one dataset file per flow.
        flow_uuid_list: list[str] = []
        for flow_uuid in sorted(flow_uuids):
            flow_data = _build_flow_data(db, flow_uuid, report)
            if flow_data:
                flow_uuid_list.append(flow_uuid)
                zf.writestr(
                    f"flows/{flow_uuid}_{dataset_version}.json",
                    json.dumps(flow_data, ensure_ascii=False, indent=2),
                )

        # Build and write process data as one dataset file per process.
        process_uuid_list: list[str] = []
        for process_uuid in sorted(process_uuids):
            process_data = _build_process_data(db, process_uuid, graph_json, report, model, flow_type_map)
            if process_data:
                process_uuid_list.append(process_uuid)
                zf.writestr(
                    f"processes/{_tidas_uuid(process_uuid)}_{dataset_version}.json",
                    json.dumps(process_data, ensure_ascii=False, indent=2),
                )

        # Build and write model data
        model_data = _build_model_data(db, model, graph_json, report)
        zf.writestr(
            f"lifecyclemodels/{project_id}_{dataset_version}.json",
            json.dumps(model_data, ensure_ascii=False, indent=2),
        )

        # Build and write manifest
        manifest = _build_manifest(project_id, flow_uuid_list, process_uuid_list)
        zf.writestr("manifest.json", json.dumps(manifest, ensure_ascii=False, indent=2))

        # Write export report
        export_report_data = report.to_dict()
        export_report_data["project_id"] = project_id
        export_report_data["project_name"] = model.name
        export_report_data["version"] = model_version.version
        export_report_data["display_lang"] = display_lang
        zf.writestr("export_report.json", json.dumps(export_report_data, ensure_ascii=False, indent=2))

    zip_buffer.seek(0)
    return zip_buffer.getvalue(), report
