# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mmr.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'mmr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmmr.proto\x12\x0ctiangong.mmr\"6\n\x0bSparseEntry\x12\x0b\n\x03row\x18\x01 \x01(\r\x12\x0b\n\x03\x63ol\x18\x02 \x01(\r\x12\r\n\x05value\x18\x03 \x01(\x01\"V\n\x0cSparseMatrix\x12\x0c\n\x04rows\x18\x01 \x01(\r\x12\x0c\n\x04\x63ols\x18\x02 \x01(\r\x12*\n\x07\x65ntries\x18\x03 \x03(\x0b\x32\x19.tiangong.mmr.SparseEntry\"\xc6\x02\n\x03MMR\x12\x13\n\x0bmmr_version\x18\x01 \x01(\t\x12\x14\n\x0cgenerated_at\x18\x02 \x01(\t\x12\x1a\n\x12source_snapshot_id\x18\x03 \x01(\t\x12\x16\n\x0esolver_version\x18\x04 \x01(\t\x12-\n\x06params\x18\x05 \x03(\x0b\x32\x1d.tiangong.mmr.MMR.ParamsEntry\x12\x15\n\rprocess_index\x18\x06 \x03(\t\x12\x1d\n\x15\x65lementary_flow_index\x18\x07 \x03(\t\x12%\n\x01\x41\x18\x08 \x01(\x0b\x32\x1a.tiangong.mmr.SparseMatrix\x12%\n\x01\x42\x18\t \x01(\x0b\x32\x1a.tiangong.mmr.SparseMatrix\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mmr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MMR_PARAMSENTRY']._loaded_options = None
  _globals['_MMR_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_SPARSEENTRY']._serialized_start=27
  _globals['_SPARSEENTRY']._serialized_end=81
  _globals['_SPARSEMATRIX']._serialized_start=83
  _globals['_SPARSEMATRIX']._serialized_end=169
  _globals['_MMR']._serialized_start=172
  _globals['_MMR']._serialized_end=498
  _globals['_MMR_PARAMSENTRY']._serialized_start=453
  _globals['_MMR_PARAMSENTRY']._serialized_end=498
# @@protoc_insertion_point(module_scope)
